# Generated by Django 5.2.10 on 2026-01-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_ats_feedback_resume_ats_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
