# Generated by Django 5.2.10 on 2026-01-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ppo_details',
            field=models.TextField(blank=True, help_text='Details about PPO eligibility, duration, stipend, etc.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ppo_offered',
            field=models.BooleanField(default=False),
        ),
    ]
