# Generated by Django 5.2.10 on 2026-01-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ats_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.FloatField(default=0.0),
        ),
    ]
