# Generated by Django 5.2.10 on 2026-01-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_ats_feedback_application_ats_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='application',
            name='ats_feedback',
            field=models.JSONField(default=dict),
        ),
    ]
